"""
    Module name :- 0001_initial
"""

# Generated by Django 4.2.9 on 2024-01-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration Details (version 0001)
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone_no", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="TeacherInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone_no", models.CharField(max_length=15)),
                ("experience", models.IntegerField()),
            ],
        ),
    ]
